name: deploy
on: 
  push:
    branches:
      - deploy
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
      
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
      
      - name: Build
        env: 
          VITE_SERVER_URL: ${{ secrets.VITE_SERVER_URL }}
        run: |
          yarn install
          yarn build
      
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
          
      - name: Deploy to S3
        run: |
          aws s3 sync ./${{ secrets.BUILD_DIRECTORY }} --region ap-northeast-2 build ${{ secrets.AWS_BUCKET_NAME }} --delete
